language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly

addons:
  postgresql: "9.3"

services:
  - postgresql
  - mysql

before_script:
  - mysql -e 'create database fnp_test;'
  - psql -c 'create database fnp_test;' -U postgres
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/phpunit/phpunit/phpunit